; Levels-
;   1 Default
; 25 Can bypass strict modes/topics
; 50 Exempt from protections
; 60 Reop/invite
; 75 Protected
; (175 CTCP DO access)

; black   Blacklisted

; dcc     Auto-accept DCCs
; auth    Auto-accept is temporary

; @ Ops (auto or pw)
; +   Voice (auto or pw)
; -    Auto de-op

; Single user level-
;   5:address
; Add non-channel levels-
;   5,=dcc:address
; Channel levels-
;   1,=#chan¬50:address
; Multiple levels-
;   5+,=#anime¬50@,=#mirc¬25:address
